// client/src/components/CTA.vue
<script lang="ts" setup>
import { defineProps, defineEmits, computed } from 'vue';
import Loader from './Loader.vue';
import style from './CTA.module.css';
const props = defineProps<{
  title: string;
  size: 'lg' | 'sm';
  type?: 'submit';
  color?: 'green' | 'red';
  loading?: boolean;
  className?: string;
  onClick?: () => void;
}>();
defineEmits<{
  (e: 'click'): void;
}>()
const buttonClass = computed(() => {
  return [
      style.cta_button,
      {
        [style.button_lg]: props.size === 'lg',
        [style.button_sm]: props.size === 'sm',
        [style.button_green]: props.color === 'green',
        [style.button_red]: props.color === 'red',
        [style.loading_button]: props.loading,
        [style.loading_button_lg]: props.loading && props.size === 'lg',
        [style.loading_button_sm]: props.loading && props.size === 'sm'
      }
    ];
});
</script>
<template>
  <button
    :class="buttonClass"
    :disabled="props.loading"
    :type="props.type"
    @click="props.onClick"
  >
    <template v-if="props.loading">
      <Loader type="btn_loader" :size="props.size" />
    </template>
    <template v-else>
      {{ props.title }}
    </template>
  </button>
</template>

// frontend/src/components/CTA.tsx
import Loader from './Loader';
import CTACSS  from './CTA.module.css';
type CTAProps = {
  title: string,
  type: 'normal_btn' | 'loading_btn',
  size: 'lg' | 'sm',
  loading?: boolean,
  onClick: React.MouseEventHandler<HTMLButtonElement>
}
const CTA = ({ title, type, size, loading, onClick }: CTAProps) => {
  return (
    <>
      {
        type == 'normal_btn' ?
          <button className={`${CTACSS.cta_button} ${size == 'lg' ? CTACSS.button_lg : CTACSS.button_sm}`} onClick={onClick}>{title}</button>
        :
        <button className={`${CTACSS.cta_button} ${CTACSS.loading_button} ${size == 'lg' ? CTACSS.loading_button_lg : CTACSS.loading_button_sm}`} onClick={onClick} disabled={loading && true}>
          { loading ? <Loader type='btn_loader' size={size}/> : title}
        </button>
      }
    </>
  );
}
export default CTA;
