// client/src/components/common/Loader.vue
<script lang="ts" setup>
import { defineProps } from 'vue';
defineProps<{
  type?: 'content_loader' | 'btn_loader';
  size?: 'lg' | 'sm';
}>();
</script>
<style src="./Loader.module.css" module/>
<template>
  <div v-if="type === 'btn_loader'">
    <div :class="[$style.loader, size === 'lg' ? $style.btn_lg_loader : $style.btn_sm_loader]"></div>
  </div>
  <div v-else :class="$style.loader_wrapper">
    <div :class="[$style.loader, $style.content_loader]"></div>
  </div>
</template>

// frontend/src/components/Loader.tsx
import LoaderCSS from './Loader.module.css';
type loaderProps = {
  type?: 'normal_loader' | 'btn_loader'
  size?: 'lg' | 'sm'
}
const Loader = ({type, size}: loaderProps) => {
  return (
    <>
      {
        type == 'btn_loader' ?
          <div className={`${LoaderCSS.loader} ${size == 'lg' ? LoaderCSS.btn_lg_loader : LoaderCSS.btn_sm_loader}`}></div>
        : 
        <div className={LoaderCSS.loader_wrapper}>
          <div className={`${LoaderCSS.loader} ${LoaderCSS.normal_loader}`}></div>
        </div>
      }
    </>
  );
}
export default Loader;
