// client/src/components/TopicAccordion.vue
<script lang="ts" setup>
import { ref, defineProps } from 'vue';
import { useTopicQuery } from '../services/topic/useTopicQuery';
import { useAuthStore } from '../stores/auth';
import { TopicStatusNamesCyrillic } from '../utils/constants';
import { TopicStatusEnum } from '../utils/enums';
import { isReportedTopic } from '../utils';
import { IconChevronDown, IconCircleDashedX } from '@tabler/icons-vue';
import type { Topic } from '../types';
import CTA from './CTA.vue';
defineProps<{ topic: Topic }>();
const { isLoadingTopicStatus, updateTopicStatus } = useTopicQuery();
const user = useAuthStore().currentUser;
const open = ref<boolean>(false);
</script>
<style module src="./TopicAccordion.module.css" />
<template>
  <div :class="$style.container">
    <div :class="$style.header" @click="open=!open">
      <div :class="$style.header_text">
        <h1>{{ topic.title }}</h1>
        <p>({{ topic.subject.title }} - {{ topic.professor.firstName }} {{ topic.professor.lastName }})</p>
      </div>
      <button :class="[$style.toggle_btn, open ? $style.rotated : '']">
        <IconChevronDown stroke={2} width="32" height="32"/>
      </button>
    </div>
    <div :class="[$style.collapse_body, open ? $style.collapse_body_open : '']">
      <div :class="$style.topic_wrapper">
        <div :class="$style.info_container">
          <div :class="$style.info_wrapper">
            <p :class="$style.body_text">
              <span>Опис: </span>
              {{ topic.description }}
            </p>
          </div>
          <div :class="$style.professor_wrapper">
            <p>Ментор</p>
            <span>{{ topic.professor.firstName }} {{ topic.professor.lastName }}</span>
          </div>
        </div>
        <div :class="$style.reported_container">
          <div :class="$style.reported_wrapper">
            <p>
              <span>Статус теме: </span>
              {{ TopicStatusNamesCyrillic[topic.status as TopicStatusEnum] }}
            </p>
            <p>
              <span>Пријављен ученик: </span>
              {{ topic.student ? topic.student.firstName + ' ' + topic.student.lastName : '/' }}
            </p>
          </div>
          <div :class="$style.cta_wrapper">
            <CTA
              v-if="topic.student === null && !isReportedTopic(topic, user.id)"
              title="Пријави тему"
              size="sm"
              :loading="isLoadingTopicStatus"
              @click="updateTopicStatus({ id: topic.id, status: TopicStatusEnum.NA_CEKANJU })"
            />
            <CTA
              v-else-if="user.id === topic.student?.userId"
              title="Одјави тему"
              size="sm"
              :loading="isLoadingTopicStatus"
              @click="updateTopicStatus({id: topic.id, status: TopicStatusEnum.SLOBODNA})"
            />
            <IconCircleDashedX v-else stroke={2} width="48" height="48" style="color: var(--red)"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/TopicAccordion.tsx
import { useState } from 'react';
import { useAccordionButton } from 'react-bootstrap';
import { topicsRegistrationApply, topicsRegistrationCancel } from '../store/topicsSlice';
import { useDispatch } from 'react-redux';
import { AppDispatch } from '../store/store';
import { Topic, User } from '../types/types';
import { ReactSVG } from 'react-svg';
import { isReportedTopic } from '../utils/utils';
import Accordion from 'react-bootstrap/Accordion';
import Card from 'react-bootstrap/Card';
import CTA from './CTA';
import arrow_icon from '../assets/arrow.svg';
import TopicAccordionCSS from './TopicAccordion.module.css';
type TopicAccordionProps = {
  type: 'topic' | 'subject',
  topic: Topic,
  subject?: Topic[],
  user: User,
  reported_topics: {
    current_number: number;
    limit: number
  }
}
type TopicAccordionToggleButtonProps = {
  eventKey: string
}
const ToggleButton = ({eventKey}: TopicAccordionToggleButtonProps) => {
  const [rotate, setRotate] = useState<boolean>(false);
  const decoratedOnClick = useAccordionButton(eventKey, () => setRotate(!rotate));
  return (
    <button type="button" className={TopicAccordionCSS.toggle_btn} onClick={decoratedOnClick}>
      <ReactSVG className={`${TopicAccordionCSS.toggle_icon} ${rotate && TopicAccordionCSS.toggle_icon_rotated}`} src={arrow_icon}/>
    </button>
  );
}
const TopicAccordion = ({type, subject, topic, reported_topics, user}: TopicAccordionProps) => {
  const dispatch = useDispatch<AppDispatch>();
  const [btnLoading, setBtnLoading] = useState({btn_id: -1, loading: false});
  const handleTopicsRegistrationApply = (topic_id: number) => {
    setBtnLoading({btn_id: topic_id, loading: true});
    dispatch(topicsRegistrationApply({"user_id": user.id, "topic_id": topic_id})).finally(() => setBtnLoading({btn_id: -1, loading: false}));
  }
  const handleTopicsRegistrationCancel = (topic_id: number) => {
    setBtnLoading({btn_id: topic_id, loading: true});
    dispatch(topicsRegistrationCancel({"user_id": user.id, "topic_id": topic_id})).finally(() => setBtnLoading({btn_id: -1, loading: false}));
  }
  return (
    <Accordion defaultActiveKey="1">
      <Card className={TopicAccordionCSS.container}>
        <Card.Header style={{position: 'relative', border: 'none'}}>
          <ToggleButton eventKey="0"/>
            <div className={TopicAccordionCSS.header_text}>
              {
                type == 'topic' ? <>
                  <h1>{topic.title}</h1>
                  <p>({topic.subject_title} - {topic.professor_username})</p>
                </> : <h1>{topic.subject_title}</h1>
              }
            </div>
          </Card.Header>
         <Accordion.Collapse eventKey="0">
          <Card.Body className={TopicAccordionCSS.card_body}>
            {
              type == 'topic' ? <>
                <div className={TopicAccordionCSS.info_container}>
                  <div className={TopicAccordionCSS.info_wrapper}>
                    <p className={TopicAccordionCSS.body_text}>
                      <span>Опис: </span>
                      {topic.info}
                    </p>
                  </div>
                  <div className={TopicAccordionCSS.professor_wrapper}>
                    <p>Ментор</p>
                    <span>{topic.professor_username}</span>
                  </div>
                </div>
                <div className={TopicAccordionCSS.reported_container}>
                  <div className={TopicAccordionCSS.reported_wrapper}>
                    <p>
                      {
                        topic.student_username && <>
                          <span>Одобрен ученик: </span>
                          {topic.student_username}
                        </>
                      }
                    </p>
                    <div className={TopicAccordionCSS.reported_users_wrapper}>
                        <span>Пријављени ученици: </span>
                      <ul>
                        {
                          topic.reportedTopicUsers.length > 0 ? 
                            topic.reportedTopicUsers.map((reported_topic, index) =>
                              <li key={index}>
                                {topic.reportedTopicUsers.length != 1 && index != 0 && ', '}
                                {reported_topic.student_username}
                              </li>
                            )
                          : <li>/</li>
                        }
                      </ul>
                    </div>
                  </div>
                  <div className={TopicAccordionCSS.cta_wrapper}>
                    {
                      isReportedTopic(topic, user.id) ?
                      <CTA title="Одјави тему" type='loading_btn' loading={btnLoading.btn_id == topic.id && btnLoading.loading}
                      size='sm' onClick={() => handleTopicsRegistrationCancel(topic.id)}
                      /> : 
                      reported_topics.current_number < reported_topics.limit ?
                      <CTA title="Пријави тему" type='loading_btn' loading={btnLoading.btn_id == topic.id && btnLoading.loading}
                        size='sm' onClick={() => handleTopicsRegistrationApply(topic.id)}
                        /> :
                        <h3 style={{color: 'var(--red)'}}>3/3</h3>
                      }
                  </div>
                </div>
              </> : <>
                {
                  subject?.map((topic, index) => (
                    <div key={index}>
                      { index > 0 && <div className={TopicAccordionCSS.line}></div> }
                      <p style={{fontSize: "1.7rem"}}>{topic.title}</p>
                      <div className={TopicAccordionCSS.info_container}>
                        <div className={TopicAccordionCSS.info_wrapper}>
                          <p className={TopicAccordionCSS.body_text}>
                            <span>Опис: </span>
                            {topic.info}
                          </p>
                        </div>
                        <div className={TopicAccordionCSS.professor_wrapper}>
                          <p>Ментор</p>
                          <span>{topic.professor_username}</span>
                        </div>
                      </div>
                      <div className={TopicAccordionCSS.reported_container}>
                        <div className={TopicAccordionCSS.reported_wrapper}>
                          <p>
                            {
                              topic.student_username && <>
                                <span>Одобрен ученик: </span>
                                {topic.student_username}
                              </>
                            }
                          </p>
                          <div className={TopicAccordionCSS.reported_users_wrapper}>
                              <span>Пријављени ученици: </span>
                            <ul>
                              {
                                topic.reportedTopicUsers.length > 0 ? 
                                  topic.reportedTopicUsers.map((reported_topic, index) =>
                                    <li key={index}>
                                      {topic.reportedTopicUsers.length != 1 && index != 0 && ', '}
                                      {reported_topic.student_username}
                                    </li>
                                  )
                                : <li>/</li>
                              }
                            </ul>
                          </div>
                        </div>
                        <div className={TopicAccordionCSS.cta_wrapper}>
                          {
                            isReportedTopic(topic, user.id) ?
                            <CTA title="Одјави тему" type='loading_btn' loading={btnLoading.btn_id == topic.id && btnLoading.loading}
                            size='sm' onClick={() => handleTopicsRegistrationCancel(topic.id)}
                            /> : 
                            reported_topics.current_number < reported_topics.limit ?
                            <CTA title="Пријави тему" type='loading_btn' loading={btnLoading.btn_id == topic.id && btnLoading.loading}
                              size='sm' onClick={() => handleTopicsRegistrationApply(topic.id)}
                            /> :
                            <h3 style={{color: 'var(--red)'}}>3/3</h3>
                          }
                        </div>
                      </div>
                    </div>
                  ))
                }
              </>
            }
            </Card.Body>
        </Accordion.Collapse>
      </Card>
    </Accordion>
  );
}
export default TopicAccordion;
