// client/src/components/NavItem.tsx
import { NavLink, useMatch, useResolvedPath } from 'react-router-dom';
import { ReactSVG } from 'react-svg';
import styles from './NavItem.module.css';
type NavItemProps = {
  title: string,
  to: string,
  icon: string
}
const NavItem = ({ title, to, icon }: NavItemProps) => {
  const closeSideBar = () => document.body.classList.remove("toggle_sidebar");
  const resolvedPath = useResolvedPath(to);
  const isActive = useMatch({ path: resolvedPath.pathname, end: true });
  return (
    <NavLink to={to} className={styles.link_wrapper} onClick={closeSideBar}>
      <div className={`${styles.nav_item} ${isActive ? styles.active : styles.not_active}`} title={title}>
        <ReactSVG src={icon} className={styles.nav_icons}/>
        <p>{title}</p>
      </div>
    </NavLink>
  );
}
export default NavItem;

// client/src/components/common/NavItem.vue
<script setup lang="ts">
import { computed, defineProps } from 'vue';
import { useRoute } from 'vue-router';
const props = defineProps<{
  title: string;
  to: string;
}>();
const route = useRoute();
const closeSideBar = () => {
  document.body.classList.remove("toggle_sidebar");
};
const isActive = computed(() => {
  return route.path === props.to;
});
</script>
<style src="./NavItem.module.css" module/>
<template>
  <router-link :to="to" :class="$style.link_wrapper" @click="closeSideBar">
    <div :class="[$style.nav_item, isActive ? $style.active : $style.not_active]" :title="title">
      <slot></slot>
      <p>{{ title }}</p>
    </div>
  </router-link>
</template>
