// client/src/layouts/PageLayout.vue
<script lang="ts" setup>
import NavBar from '../components/NavBar.vue';
import SideBar from '../components/SideBar.vue';
</script>
<style src="./PageLayout.module.css" module/>
<template>
    <NavBar />
    <SideBar />
    <main id='mainWrapper' :class=$style.main_wrapper>
        <slot></slot>
    </main>
</template>

// client/src/layouts/PageLayout.tsx
import NavBar from '../components/NavBar';
import SideBar from '../components/SideBar';
import styles from './PageLayout.module.css';
const PageLayout = ({ children }: { children: JSX.Element }) => {
  return (
    <>
      <NavBar/>
      <SideBar/>
      <main id='mainWrapper' className={styles.main_wrapper}>
        { children }
      </main>
    </>
  );
}
export default PageLayout;
