// client/src/components/CTA.tsx
import Loader from './Loader';
import classNames from 'classnames';
import styles from './CTA.module.css';
interface CTAProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  title: string;
  size: 'lg' | 'sm';
  color?: 'green' | 'red';
  loading?: boolean;
  onClick: React.MouseEventHandler<HTMLButtonElement>;
}
const CTA = ({ title, size, color, loading = false, onClick, className, ...props }: CTAProps) => {
  const buttonClass = classNames(styles.cta_button, className, {
    [styles.button_lg]: size === 'lg',
    [styles.button_sm]: size === 'sm',
    [styles.button_green]: color === 'green',
    [styles.button_red]: color === 'red',
    [styles.loading_button]: loading,
    [styles.loading_button_lg]: loading && size === 'lg',
    [styles.loading_button_sm]: loading && size === 'sm',
  });
  return (
    <button className={buttonClass} onClick={onClick} disabled={loading} {...props}>
      {loading ? <Loader type="btn_loader" size={size} /> : title}
    </button>
  );
};
export default CTA;

// client/src/components/CTA.vue
<script lang="ts" setup>
import { defineProps, defineEmits, computed } from 'vue';
import Loader from './Loader.vue';
import style from './CTA.module.css';
const props = defineProps<{
  title: string;
  size: 'lg' | 'sm';
  type?: 'submit';
  color?: 'green' | 'red';
  loading?: boolean;
  className?: string;
  onClick?: () => void;
}>();
defineEmits<{
  (e: 'click'): void;
}>()
const buttonClass = computed(() => {
  return [
      style.cta_button,
      {
        [style.button_lg]: props.size === 'lg',
        [style.button_sm]: props.size === 'sm',
        [style.button_green]: props.color === 'green',
        [style.button_red]: props.color === 'red',
        [style.loading_button]: props.loading,
        [style.loading_button_lg]: props.loading && props.size === 'lg',
        [style.loading_button_sm]: props.loading && props.size === 'sm'
      }
    ];
});
</script>
<template>
  <button
    :class="buttonClass"
    :disabled="props.loading"
    :type="props.type"
    @click="props.onClick"
  >
    <template v-if="props.loading">
      <Loader type="btn_loader" :size="props.size" />
    </template>
    <template v-else>
      {{ props.title }}
    </template>
  </button>
</template>
