// client/src/components/layout/NavBar.vue
<script lang="ts" setup>
import { ref } from 'vue';
import { onClickOutside } from '@vueuse/core';
import { useAuthStore } from '../../stores/auth';
import { useAuth } from '../../composables/queries/useAuth';
import { useModal } from '../../composables/utils/useModal';
import { usePanel } from '../../composables/utils/usePanel';
import { useTheme } from '../../composables/utils/useTheme';
import { RoleNamesCyrillic, themes } from '../../utils/constants';
import ChatsPanel from '../layout/ChatsPanel.vue';
import NotificationsPanel from '../layout/NotificationsPanel.vue';
import IconButton from '../common/IconButton.vue';
import DropDown from './DropDown.vue';
import Modal from '../layout/Modal.vue';
import Logo from '../common/Logo.vue';
import CTA from '../common/CTA.vue';
import {
  IconBell,
  IconChevronDown,
  IconLogout,
  IconMenu2,
  IconMessages,
  IconMoon,
  IconSun,
  IconUserCircle
} from '@tabler/icons-vue';
const auth = useAuthStore();
const { logout: handleLogout } = useAuth();
const { modalRef, openModal } = useModal();
const { theme, toggleTheme } = useTheme();
const { chatsRef, notificationsRef, openPanel } = usePanel();
const isDropdownVisible = ref(false);
const dropdownRef = ref<HTMLElement | null>(null);
const toggleSideBar = () => document.body.classList.toggle("toggle_sidebar");
onClickOutside(dropdownRef, () => isDropdownVisible.value = false);
</script>
<style src="./NavBar.module.css" module/>
<template>
  <header :class="$style.nav_wrapper">
    <div :class="$style.left_side">
      <Logo />
      <IconButton @click="toggleSideBar">
        <IconMenu2 stroke={2} width="32" height="32"/>
      </IconButton>
    </div>
    <div :class="$style.right_side">
      <IconButton @click="toggleTheme">
        <IconSun v-if="theme === themes.dark" stroke={2} width="32" height="32" />
        <IconMoon v-else stroke={2} width="32" height="32" />
      </IconButton>
      <IconButton @click="openPanel('notifications')">
        <NotificationsPanel ref="notificationsRef">
          <IconBell stroke={2} width="32" height="32" />
        </NotificationsPanel>
      </IconButton>
      <IconButton @click="openPanel('chats')">
        <ChatsPanel ref="chatsRef">
          <IconMessages stroke={2} width="32" height="32" />
        </ChatsPanel>
      </IconButton>
      <div ref="dropdownRef">
        <button :class="$style.profile_btn" @click="isDropdownVisible = !isDropdownVisible">
          {{ auth.currentUser.firstName }} {{ auth.currentUser.lastName }}
          <IconChevronDown stroke={2} width="32" height="32" :class="[$style.toggle_icon, isDropdownVisible ? $style.rotated : '']"/>
        </button>
        <DropDown :visible="isDropdownVisible">
          <div :class="$style.profile_drop_wrapper">
            <IconUserCircle stroke={2} />
            <p :class="$style.username">{{ auth.currentUser.firstName }} {{ auth.currentUser.lastName }}</p>
            <p :class="$style.status">{{ RoleNamesCyrillic[auth.userRole] }}</p>
          </div>
          <router-link to="/profile">
            <li>
              <IconUserCircle stroke={2} />
              Мој Профил
            </li>
          </router-link>
          <li @click="openModal">
            <Modal ref="modalRef" title="Одјава">
              <template #open>
                <IconLogout stroke={2} color="red"/>
                Одјави се
              </template>
              <p>Да ли сте сигурни да желите да се одјавите?</p>
              <template #footer>
                <CTA title="Одјави се" color="red" size="sm" :onClick="handleLogout"/>
              </template>
            </Modal>
          </li>
        </DropDown>
      </div>
    </div>
  </header>
</template>

// client/src/components/NavBar.tsx
import { useEffect, useRef, useState } from "react";
import { NavLink } from "react-router-dom";
import { Divide as Hamburger } from "hamburger-react";
import { useAuthContext } from "../context/AuthContext";
import { roleEnum } from "../utils/constants";
import { getCyrillicName } from "../utils/helpers";
import { ModalHandle } from "../types/types";
import { ReactSVG } from "react-svg";
import useLogOut from "../services/api/useLogOut";
import Notifications from "./Notifications";
import Logo from "./Logo";
import Chats from "./Chats";
import DropDown from "./DropDown";
import hamburger_icon from "../assets/hamburger.svg";
import profile_icon from "../assets/profile.svg";
import logout_icon from "../assets/logout.svg";
import styles from "./NavBar.module.css";
import Modal from "./Modal";
import CTA from "./CTA";
const NavBar = () => {
  const { currentUser } = useAuthContext();
  const logOut = useLogOut();
  const [isOpen, setOpen] = useState(false);
  const modal = useRef<ModalHandle>(null);
  const toggleSideBar = () => document.body.classList.toggle("toggle_sidebar");
  const toggleHamburger = () => {
    toggleSideBar();
    setOpen(!isOpen);
  };
  const logOutSubmit = async () => await logOut();
  useEffect(() => {
    setOpen(document.body.className === "toggle_sidebar");
  }, [document.body.className]);
  return (
    <>
      <Modal
        ref={modal}
        title="Одјава"
        body="Да ли сте сигурни да желите да се одјавите?"
        CTA={
          <CTA title="Одјави се" color="red" size="sm" onClick={logOutSubmit} />
        }
      />
      <header className={styles.nav_wrapper}>
        <div className={styles.left_side}>
          <Logo />
          <button onClick={toggleSideBar}>
            <ReactSVG
              src={hamburger_icon}
              className={styles.nav_icons_fill_hamburger}
            />
          </button>
          <div className={styles.hamburger_wrapper}>
            <Hamburger
              color="var(--text-prim)"
              rounded
              toggled={isOpen}
              toggle={toggleHamburger}
            />
          </div>
        </div>
        <div className={styles.right_side}>
          <Notifications type="icon" />
          <Chats type="icon" />
          <DropDown title={`${currentUser?.firstName} ${currentUser?.lastName}`}>
            <div className={styles.dropdown}>
              <div className={styles.dropdown_header}>
                <p className={styles.username}>
                  {currentUser?.firstName} {currentUser?.lastName}
                </p>
                <p className={styles.status}>
                  {getCyrillicName(roleEnum, currentUser.roleStatus)}
                </p>
              </div>
              <NavLink
                to="/profile"
                className={styles.profile_btn}
                title="Мој профил"
              >
                <ReactSVG
                  src={profile_icon}
                  className={styles.nav_icons_fill_profile}
                />
                <p>Мој профил</p>
              </NavLink>
              <button
                onClick={() => modal.current?.open()}
                className={styles.logout_btn}
                title="Одјави се"
              >
                <ReactSVG src={logout_icon} className={styles.logout_icon} />
                Одјави се
              </button>
            </div>
          </DropDown>
        </div>
      </header>
    </>
  );
};
export default NavBar;
