// client/src/components/SideBar.tsx
import { useRef } from 'react';
import { ReactSVG } from 'react-svg';
import { ModalHandle } from '../types/types';
import { useAuthContext } from '../context/AuthContext';
import { roleEnum } from '../utils/constants';
import useLogOut from '../services/api/useLogOut';
import NavItem from './NavItem';
import Notifications from './Notifications';
import Chats from './Chats';
import CTA from './CTA';
import Modal from './Modal';
import home_icon from '../assets/home.svg';
import theme_icon from '../assets/theme.svg';
import profile_icon from '../assets/profile.svg';
import add_icon from '../assets/add.svg';
import logout_icon from '../assets/logout.svg';
import styles from './SideBar.module.css';
const SideBar = () => {
    const { currentUser } = useAuthContext();
    const logOut = useLogOut();
    const logOutSubmit = async () => await logOut();
    const modal = useRef<ModalHandle>(null);
    return (
        <aside id='sideBar' className={styles.sidebar_container}>
            <main className={styles.main_wrapper}>
                <div className={styles.nav_items}>
                    <NavItem title='Почетна' to='/' icon={home_icon}/>
                    {
                        currentUser.roleStatus == roleEnum.UCENIK.id && <>
                            <NavItem title='Теме' to='/student/topics' icon={theme_icon}/>
                        </>
                    }
                    {
                        currentUser.roleStatus == roleEnum.PROFESOR.id && <>
                            <NavItem title='Теме' to='/professor/topics' icon={theme_icon}/>
                            <NavItem title='Додај Тему' to='/topics/create' icon={add_icon}/>
                        </>
                    }
                    <NavItem title='Мој Профил' to='/profile' icon={profile_icon}/>
                </div>
                <div className={styles.nav_buttons}>
                    <Chats/>
                    <Notifications/>
                    <button
                        onClick={() => modal.current?.open()}
                        className={styles.logout_btn}
                        title="Одјави се"
                    >
                        <ReactSVG src={logout_icon} className={styles.logout_icon} />
                        Одјави се
                    </button>
                    <Modal
                        ref={modal}
                        title="Одјава"
                        body="Да ли сте сигурни да желите да се одјавите?"
                        CTA={
                        <CTA title="Одјави се" color="red" size="sm" onClick={logOutSubmit} />
                        }
                    />
                </div>
            </main>
        </aside>
    );
}
export default SideBar;

// client/src/components/SideBar.vue
<script lang="ts" setup>
import { useRouter } from 'vue-router';
import { useAuthStore } from '../stores/auth';
import { useModal } from '../composables/useModal';
import { RoleEnum } from '../utils/enums';
import NavItem from './NavItem.vue';
import Modal from './Modal.vue';
import CTA from './CTA.vue';
import {
    IconArticle,
    IconCirclePlus,
    IconHome,
    IconLogout,
    IconUserCircle
} from '@tabler/icons-vue';
const { modalRef, openModal } = useModal();
const auth = useAuthStore();
const router = useRouter();
const handleLogout = async () => {
  await auth.logout();
  router.push('/login');
};
</script>
<style src="./SideBar.module.css" module/>
<template>
    <aside id="sideBar" :class="$style.sidebar_container">
        <main :class="$style.main_wrapper">
            <div :class="$style.nav_items">
                <NavItem title="Почетна" to="/">
                    <IconHome stroke={2} />
                </NavItem>
                <NavItem v-if="auth.userRole == RoleEnum.UCENIK" title="Теме" to="/topics">
                    <IconArticle stroke={2} />
                </NavItem>
                <NavItem v-if="auth.userRole == RoleEnum.PROFESOR" title="Пријављене Теме" to="/topics/reported">
                    <IconArticle stroke={2} />
                </NavItem>
                <NavItem v-if="auth.userRole == RoleEnum.PROFESOR" title="Додај Тему" to="/topics/create">
                    <IconCirclePlus stroke={2} />
                </NavItem>
                <NavItem title="Мој Профил" to="/profile">
                    <IconUserCircle stroke={2} />
                </NavItem>
            </div>
            <div :class="$style.nav_buttons">
                <Modal ref="modalRef" title="Одјава">
                    <template #open>
                        <button :class="$style.logout_btn" @click="openModal">
                            <IconLogout stroke={2} color="red"/>
                            Одјави се
                        </button>
                    </template>
                    <p>Да ли сте сигурни да желите да се одјавите?</p>
                    <template #footer>
                        <CTA title="Одјави се" color="red" size="sm" :onClick="handleLogout"/>
                    </template>
                </Modal>
            </div>
        </main>
    </aside>
</template>
