// client/src/components/TopicAccordion.vue
<script lang="ts" setup>
import { ref, defineProps } from 'vue';
import { useTopicQuery } from '../services/topic/useTopicQuery';
import { useAuthStore } from '../stores/auth';
import { TopicStatusNamesCyrillic } from '../utils/constants';
import { TopicStatusEnum } from '../utils/enums';
import { isReportedTopic } from '../utils';
import { IconChevronDown, IconCircleDashedX } from '@tabler/icons-vue';
import type { Topic } from '../types';
import CTA from './CTA.vue';
defineProps<{ topic: Topic }>();
const { isLoadingTopicStatus, updateTopicStatus } = useTopicQuery();
const user = useAuthStore().currentUser;
const open = ref<boolean>(false);
</script>
<style module src="./TopicAccordion.module.css" />
<template>
  <div :class="$style.container">
    <div :class="$style.header" @click="open=!open">
      <div :class="$style.header_text">
        <h1>{{ topic.title }}</h1>
        <p>({{ topic.subject.title }} - {{ topic.professor.firstName }} {{ topic.professor.lastName }})</p>
      </div>
      <button :class="[$style.toggle_btn, open ? $style.rotated : '']">
        <IconChevronDown stroke={2} width="32" height="32"/>
      </button>
    </div>
    <div :class="[$style.collapse_body, open ? $style.collapse_body_open : '']">
      <div :class="$style.topic_wrapper">
        <div :class="$style.info_container">
          <div :class="$style.info_wrapper">
            <p :class="$style.body_text">
              <span>Опис: </span>
              {{ topic.description }}
            </p>
          </div>
          <div :class="$style.professor_wrapper">
            <p>Ментор</p>
            <span>{{ topic.professor.firstName }} {{ topic.professor.lastName }}</span>
          </div>
        </div>
        <div :class="$style.reported_container">
          <div :class="$style.reported_wrapper">
            <p>
              <span>Статус теме: </span>
              {{ TopicStatusNamesCyrillic[topic.status as TopicStatusEnum] }}
            </p>
            <p>
              <span>Пријављен ученик: </span>
              {{ topic.student ? topic.student.firstName + ' ' + topic.student.lastName : '/' }}
            </p>
          </div>
          <div :class="$style.cta_wrapper">
            <CTA
              v-if="topic.student === null && !isReportedTopic(topic, user.id)"
              title="Пријави тему"
              size="sm"
              :loading="isLoadingTopicStatus"
              @click="updateTopicStatus({ id: topic.id, status: TopicStatusEnum.NA_CEKANJU })"
            />
            <CTA
              v-else-if="user.id === topic.student?.userId"
              title="Одјави тему"
              size="sm"
              :loading="isLoadingTopicStatus"
              @click="updateTopicStatus({id: topic.id, status: TopicStatusEnum.SLOBODNA})"
            />
            <IconCircleDashedX v-else stroke={2} width="48" height="48" style="color: var(--red)"/>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// client/src/components/TopicAccordion.tsx
import { useState } from 'react';
import { useTopicService } from '../services/api/useTopicService';
import { getCyrillicName, isReportedTopic } from '../utils/helpers';
import { topicStatusEnum } from '../utils/constants';
import { Topic, User } from '../types/types';
import { ReactSVG } from 'react-svg';
import CTA from './CTA';
import arrow_icon from '../assets/arrow.svg';
import styles from './TopicAccordion.module.css';
type TopicAccordionProps = {
  topic: Topic,
  isRegisteredStudent: boolean,
  user: User,
};
const TopicAccordion = ({ topic, user, isRegisteredStudent }: TopicAccordionProps) => {
  const { updateTopicAsync } = useTopicService();
  const [btnLoading, setBtnLoading] = useState({ btn_id: -1, loading: false });
  const [open, setOpen] = useState(false);
  const handleTopicUpdate = async (topic_id: number, user_id: number) => {
    setBtnLoading({ btn_id: topic_id, loading: true });
    await updateTopicAsync({ id: topic_id, userId: user_id }).finally(() => setBtnLoading({ btn_id: -1, loading: false }));
  };
  return (
    <div className={styles.container}>
      <div className={styles.header} onClick={() => setOpen(!open)}>
        <div className={styles.header_text}>
            <h1>{topic.title}</h1>
            <p>({topic.subjectTitle} - {topic.professorUsername})</p>
        </div>
        <button type="button" className={styles.toggle_btn}>
          <ReactSVG
            className={`${styles.toggle_icon} ${open ? styles.toggle_icon_rotated : ''}`}
            src={arrow_icon}
          />
        </button>
      </div>
      <div className={`${styles.collapse_body} ${open ? styles.collapse_body_open : ''}`}>
        {
          <div className={styles.topic_wrapper}>
            <div className={styles.info_container}>
              <div className={styles.info_wrapper}>
                <p className={styles.body_text}>
                  <span>Опис: </span>
                  {topic.description}
                </p>
              </div>
              <div className={styles.professor_wrapper}>
                <p>Ментор</p>
                <span>{topic.professorUsername}</span>
              </div>
            </div>
            <div className={styles.reported_container}>
              <div className={styles.reported_wrapper}>
                <p>
                  {
                    topic.status &&
                    <>
                      <span>Статус теме: </span>
                      {getCyrillicName(topicStatusEnum, topic.status)}
                    </>
                  }
                </p>
                <div className={styles.reported_users_wrapper}>
                  <span>Пријављен ученик: {topic.studentUsername || '/'}</span>
                </div>
              </div>
              <div className={styles.cta_wrapper}>
                {
                  isReportedTopic(topic, user.id) ?
                  <CTA
                    title="Одјави тему"
                    loading={btnLoading.btn_id === topic.id && btnLoading.loading}
                    size="sm"
                    onClick={() => handleTopicUpdate(topic.id, user.id)}
                  /> : topic.studentUserId === null && !isRegisteredStudent ?
                  <CTA
                    title="Пријави тему"
                    loading={btnLoading.btn_id === topic.id && btnLoading.loading}
                    size="sm"
                    onClick={() => handleTopicUpdate(topic.id, user.id)}
                  /> : <h1 style={{ color: 'var(--red)' }}>1/1</h1>
                }
              </div>
            </div>
          </div> 
        }
      </div>
    </div>
  )
}
export default TopicAccordion;
